name: Build and Scan Node.js Application

on:
  - push
   
jobs:
  build:
    name: Build and Create Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install
      
      - name: Run Tests
        run: npm test

      - name: Build Application
        run: npm run build || echo "No build step required"

      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-world-artifact
          path: .
          retention-days: 5

  scan:
    name: Scan with SonarQube
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: hello-world-artifact

      - name: Set up SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner-cli-4.7.0.2747-linux.zip -d $HOME/
          echo "export PATH=$HOME/sonar-scanner-4.7.0.2747-linux/bin:$PATH" >> $GITHUB_ENV

      - name: Run SonarQube Scanner
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=hello-world \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
